# Generated by Django 5.2.8 on 2025-12-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="creator_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discussion",
            name="creator_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
