# Generated by Django 5.2.8 on 2025-12-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_coursediscussion_coursecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursediscussion',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        
    ]
